<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Polymarket Signals — Calibration Dashboard</title>
<style>
  :root { --bg: #0d1117; --surface: #161b22; --border: #30363d;
           --text: #c9d1d9; --text-dim: #8b949e; --accent: #58a6ff;
           --green: #3fb950; --red: #f85149; --yellow: #d29922; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
         background: var(--bg); color: var(--text); line-height: 1.5; padding: 20px; }
  .header { text-align: center; margin-bottom: 24px; }
  .header h1 { font-size: 1.5rem; color: var(--accent); margin-bottom: 8px; }
  .header .stats { display: flex; justify-content: center; gap: 24px; flex-wrap: wrap; }
  .header .stat { background: var(--surface); border: 1px solid var(--border);
                  border-radius: 8px; padding: 12px 20px; min-width: 120px; }
  .header .stat .label { color: var(--text-dim); font-size: 0.8rem; text-transform: uppercase; }
  .header .stat .value { font-size: 1.4rem; font-weight: 600; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
          gap: 20px; max-width: 1400px; margin: 0 auto; }
  .panel { background: var(--surface); border: 1px solid var(--border);
           border-radius: 8px; padding: 16px; }
  .panel h2 { font-size: 1rem; color: var(--accent); margin-bottom: 12px;
              border-bottom: 1px solid var(--border); padding-bottom: 8px; }
  .panel-wide { grid-column: 1 / -1; }
  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
  th { text-align: left; color: var(--text-dim); font-weight: 500; padding: 6px 8px;
       border-bottom: 1px solid var(--border); }
  td { padding: 6px 8px; border-bottom: 1px solid var(--border); }
  tr:hover { background: rgba(88,166,255,0.05); }
  .edge-pos { color: var(--green); }
  .edge-neg { color: var(--red); }
  .empty-state { text-align: center; color: var(--text-dim); padding: 40px 20px;
                 font-size: 1.1rem; }
  .banner { background: rgba(210,153,34,0.15); border: 1px solid var(--yellow);
            color: var(--yellow); text-align: center; padding: 10px; border-radius: 6px;
            margin-bottom: 16px; font-size: 0.9rem; }
  .footer { text-align: center; color: var(--text-dim); font-size: 0.75rem;
            margin-top: 24px; }
  @media (max-width: 600px) {
    .grid { grid-template-columns: 1fr; }
    .header .stats { flex-direction: column; align-items: center; }
  }
</style>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js" crossorigin="anonymous"></script>
<script id="__METRICS__" type="application/json">$JSON_DATA</script>
</head>
<body>
<noscript><div class="empty-state">JavaScript required to render dashboard charts.</div></noscript>
<div class="header">
  <h1>Polymarket Signals — Calibration Dashboard</h1>
  <div class="stats" id="header-stats"></div>
</div>
$BANNER
<div class="grid">
  <div class="panel panel-wide" id="panel-calibration">
    <h2>Calibration Curve</h2>
    <div id="chart-calibration"></div>
  </div>
  <div class="panel" id="panel-brier-bar">
    <h2>Brier Score by Category</h2>
    <div id="chart-brier-bar"></div>
  </div>
  <div class="panel" id="panel-brier-time">
    <h2>Brier Over Time</h2>
    <div id="chart-brier-time"></div>
  </div>
  <div class="panel" id="panel-edge">
    <h2>Edge Distribution (LLM − Market)</h2>
    <div id="chart-edge"></div>
  </div>
  <div class="panel" id="panel-active">
    <h2>Active Signals (|edge| ≥ $EDGE_THRESHOLD%)</h2>
    <div id="table-active"></div>
  </div>
  <div class="panel" id="panel-recent">
    <h2>Recent Predictions</h2>
    <div id="table-recent"></div>
  </div>
  <div class="panel" id="panel-health">
    <h2>Resolution Health</h2>
    <div id="table-health"></div>
  </div>
</div>
<div class="footer">Last updated: $LAST_UPDATED · Generated by Hermes polymarket-signals</div>
<script>
// Dashboard rendering logic — all data comes from __METRICS__ JSON
(function() {
  'use strict';
  var el = document.getElementById('__METRICS__');
  if (!el) return;
  var m = JSON.parse(el.textContent);

  // ── Helpers ──
  var DARK_LAYOUT = { paper_bgcolor: '#0d1117', plot_bgcolor: '#161b22',
    font: { color: '#c9d1d9' }, margin: { t: 30, b: 40, l: 50, r: 20 } };
  var DARK_AXES = { gridcolor: '#30363d', zerolinecolor: '#484f58', tickfont: { color: '#8b949e' } };
  var PLOTLY_CFG = { displayModeBar: false, responsive: true };
  function fmtPct(v) { return v != null ? (v * 100).toFixed(1) + '%' : '—'; }
  function esc(s) { var d = document.createElement('div'); d.textContent = s; return d.innerHTML; }
  function tsShort(t) { return t ? t.replace('T', ' ').substring(0, 16) : '—'; }

  // ── Header Stats ──
  (function() {
    var c = document.getElementById('header-stats');
    var items = [
      { label: 'Total', value: m.total_predictions },
      { label: 'Resolved', value: m.resolved_count },
      { label: 'Pending', value: m.pending_count },
      { label: 'Mean Brier', value: m.mean_brier != null ? m.mean_brier.toFixed(4) : 'Collecting' },
      { label: 'Last Scan', value: tsShort(m.last_scan_ts) }
    ];
    c.innerHTML = items.map(function(i) {
      return '<div class="stat"><div class="label">' + i.label + '</div><div class="value">' + i.value + '</div></div>';
    }).join('');
  })();

  // ── Calibration Curve ──
  (function() {
    var cal = m.calibration || [];
    var resolved = m.resolved_count || 0;
    var el = document.getElementById('chart-calibration');
    if (resolved < 30) {
      el.innerHTML = '<div class="empty-state">Collecting resolved predictions (' + resolved + '/30 minimum for significant curve)</div>';
      return;
    }
    var bins = cal.filter(function(b) { return b.n > 0; });
    var preds = bins.map(function(b) { return (b.bin_lo + b.bin_hi) / 2; });
    var actuals = bins.map(function(b) { return b.freq; });
    var ns = bins.map(function(b) { return b.n; });
    var diag = [0, 1];
    var traces = [
      { x: preds, y: actuals, mode: 'markers+lines', name: 'Actual',
        text: ns.map(function(n) { return 'n=' + n; }), marker: { size: ns.map(function(n) { return Math.min(20, Math.max(5, n)); }) } },
      { x: diag, y: diag, mode: 'lines', name: 'Perfect', line: { dash: 'dash', color: '#8b949e' } }
    ];
    Plotly.newPlot(el, traces, Object.assign({}, DARK_LAYOUT, {
      xaxis: Object.assign({}, DARK_AXES, { title: 'Predicted P', range: [0, 1] }),
      yaxis: Object.assign({}, DARK_AXES, { title: 'Actual Frequency', range: [0, 1] }),
      showlegend: true
    }), PLOTLY_CFG);
  })();

  // ── Brier Bar (per-category) ──
  (function() {
    var bp = m.brier || {};
    var pc = bp.per_category || {};
    var cats = Object.keys(pc);
    var el = document.getElementById('chart-brier-bar');
    if (cats.length === 0) {
      el.innerHTML = '<div class="empty-state">No resolved predictions yet</div>';
      return;
    }
    var trace = { x: cats, y: cats.map(function(c) { return pc[c]; }),
                  type: 'bar', marker: { color: '#58a6ff' } };
    Plotly.newPlot(el, [trace], Object.assign({}, DARK_LAYOUT, {
      xaxis: DARK_AXES, yaxis: Object.assign({}, DARK_AXES, { title: 'Brier Score' })
    }), PLOTLY_CFG);
  })();

  // ── Brier Over Time ──
  (function() {
    var rp = m.resolved_predictions || [];
    var el = document.getElementById('chart-brier-time');
    if (rp.length === 0) {
      el.innerHTML = '<div class="empty-state">No resolved predictions yet</div>';
      return;
    }
    // Group by week from resolved_ts
    var weeks = {};
    rp.forEach(function(p) {
      if (!p.resolved_ts) return;
      var w = p.resolved_ts.substring(0, 10); // day-level granularity
      if (!weeks[w]) weeks[w] = [];
      weeks[w].push(Math.pow(p.predicted_p - p.outcome_int, 2));
    });
    var dates = Object.keys(weeks).sort();
    var means = dates.map(function(d) {
      var errs = weeks[d];
      return errs.reduce(function(a, b) { return a + b; }, 0) / errs.length;
    });
    var trace = { x: dates, y: means, mode: 'lines+markers', name: 'Mean Brier',
                  line: { color: '#d29922' } };
    Plotly.newPlot(el, [trace], Object.assign({}, DARK_LAYOUT, {
      xaxis: DARK_AXES, yaxis: Object.assign({}, DARK_AXES, { title: 'Brier Score' })
    }), PLOTLY_CFG);
  })();

  // ── Edge Distribution ──
  (function() {
    var ed = m.edge_distribution || {};
    var hist = ed.histogram || [];
    var el = document.getElementById('chart-edge');
    if (hist.length === 0) {
      el.innerHTML = '<div class="empty-state">No edge data yet</div>';
      return;
    }
    var x = hist.map(function(b) { return (b.bin_lo + b.bin_hi) / 2; });
    var trace = { x: x, y: hist.map(function(b) { return b.count; }),
                  type: 'bar', marker: { color: '#3fb950' } };
    Plotly.newPlot(el, [trace], Object.assign({}, DARK_LAYOUT, {
      xaxis: Object.assign({}, DARK_AXES, { title: 'Edge (LLM − Market)' }),
      yaxis: Object.assign({}, DARK_AXES, { title: 'Count' })
    }), PLOTLY_CFG);
  })();

  // ── Active Signals Table ──
  (function() {
    var sigs = m.active_signals || [];
    var el = document.getElementById('table-active');
    if (sigs.length === 0) {
      el.innerHTML = '<div class="empty-state">No active signals above threshold</div>';
      return;
    }
    var html = '<table><tr><th>Market</th><th>Category</th><th>LLM P</th><th>Market P</th><th>Edge</th><th>Scan</th></tr>';
    sigs.forEach(function(s) {
      var cls = s.edge > 0 ? 'edge-pos' : 'edge-neg';
      html += '<tr><td title="' + esc(s.condition_id) + '">' + esc(s.question).substring(0, 60) + '</td>'
        + '<td>' + esc(s.category) + '</td>'
        + '<td>' + fmtPct(s.predicted_p) + '</td>'
        + '<td>' + fmtPct(s.market_p) + '</td>'
        + '<td class="' + cls + '">' + (s.edge > 0 ? '+' : '') + (s.edge * 100).toFixed(1) + '%</td>'
        + '<td>' + tsShort(s.scan_ts) + '</td></tr>';
    });
    html += '</table>';
    el.innerHTML = html;
  })();

  // ── Recent Predictions Table ──
  (function() {
    var rp = m.recent_predictions || [];
    var el = document.getElementById('table-recent');
    if (rp.length === 0) {
      el.innerHTML = '<div class="empty-state">No predictions yet</div>';
      return;
    }
    var html = '<table><tr><th>Market</th><th>Category</th><th>LLM P</th><th>Market P</th><th>Outcome</th><th>Result</th></tr>';
    rp.forEach(function(r) {
      var outcome = r.outcome_int != null ? ('Yes' : 'No') : 'Pending';
      var hit = r.outcome_int != null
        ? (Math.abs(r.predicted_p - r.outcome_int) < 0.5 ? '<span class="edge-pos">Hit</span>' : '<span class="edge-neg">Miss</span>')
        : '—';
      html += '<tr><td>' + esc(r.question).substring(0, 50) + '</td>'
        + '<td>' + esc(r.category) + '</td>'
        + '<td>' + fmtPct(r.predicted_p) + '</td>'
        + '<td>' + fmtPct(r.market_p) + '</td>'
        + '<td>' + outcome + '</td>'
        + '<td>' + hit + '</td></tr>';
    });
    html += '</table>';
    el.innerHTML = html;
  })();

  // ── Resolution Health ──
  (function() {
    var h = m.resolution_health || {};
    var el = document.getElementById('table-health');
    var html = '<table><tr><th>Status</th><th>Count</th></tr>'
      + '<tr><td>Resolved</td><td>' + (h.resolved || 0) + '</td></tr>'
      + '<tr><td>Pending</td><td>' + (h.pending || 0) + '</td></tr>'
      + '<tr><td>Disputed</td><td>' + (h.disputed_count || 0) + '</td></tr></table>';
    if (h.disputed && h.disputed.length > 0) {
      html += '<h3 style="color:var(--yellow);margin-top:12px;font-size:0.85rem">Disputed Markets</h3>';
      html += '<table><tr><th>Market</th><th>Status</th></tr>';
      h.disputed.forEach(function(d) {
        html += '<tr><td>' + esc(d.question).substring(0, 60) + '</td><td>' + esc(d.resolution_status) + '</td></tr>';
      });
      html += '</table>';
    }
    el.innerHTML = html;
  })();
})();
</script>
</body>
</html>
